server.port=9090
# docker run --name contacommand -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=senha -e POSTGRES_DB=contacommand -p5432:5432 -d postgres 
spring.application.name=msconta
#spring.datasource.url=jdbc:postgresql://localhost:5432/contacommand
spring.datasource.username=postgres
#spring.datasource.password=senha
spring.datasource.driver-class-name=org.postgresql.Driver

#Carol
spring.datasource.url=jdbc:postgresql://localhost:5433/msconta
spring.datasource.password=admin

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true