spring.application.name=msgerente

server.port=8083

spring.datasource.url=${BD_GERENTE_URL}
spring.datasource.username=${BD_GERENTE_USUARIO}
spring.datasource.password=${BD_GERENTE_SENHA}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBIT_MQ_USUARIO}
spring.rabbitmq.password=${RABBIT_MQ_SENHA}

spring.config.import=optional:application-local.properties