spring.application.name=msauth2

server.port=5000

spring.mongodb.uri=mongodb://localhost:27017/msauth2

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBIT_MQ_USUARIO}
spring.rabbitmq.password=${RABBIT_MQ_SENHA}

api.security.token.secret=${JWT_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USUARIO}
spring.mail.password=${EMAIL_SENHA}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.config.import=optional:application-local.properties
