spring.application.name=msauth2

server.port=5000

spring.mongodb.uri=mongodb://localhost:27017/msauth2

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBIT_MQ_USUARIO}
spring.rabbitmq.password=${RABBIT_MQ_SENHA}

api.security.token.secret=${JWT_SECRET}

spring.config.import=optional:application-local.properties
