spring.application.name=mscliente2

server.port=8082

spring.datasource.url=${BD_CLIENTE_URL}
spring.datasource.username=${BD_CLIENTE_USUARIO}
spring.datasource.password=${BD_CLIENTE_SENHA}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBIT_MQ_USUARIO}
spring.rabbitmq.password=${RABBIT_MQ_SENHA}

spring.config.import=optional:application-local.properties