spring.application.name=saga

server.port=8084

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBIT_MQ_USUARIO}
spring.rabbitmq.password=${RABBIT_MQ_SENHA}

spring.config.import=optional:application-local.properties